# This docking config file provides the mock docker a series of known paths which
# the cleaner robot will follow during a docking (aka cleaning) process. 
#   Example:  Destination: "CLEANZONE" ;  The path here is the trajactory 
#             which starts from "CLEANZONE_start" to "CLEANZONE"
#
# Note: These waypoints are in (x meters, y meters, yaw radian) form
#
# If loaded correctly, you will be able to echo the msg via:
#   ros2 topic echo /dock_summary --qos-durability transient_local --qos-reliability reliable
#
# Configuring Cleaning path:
#    The full cleaning path which the robot will travel along. When configuring, the first
#    waypoint is required to be the current robot's waypoint.
#    And the last waypoint should the exact same waypoint as 'finish_waypoint'

UzRobot:
  clean_zone: 
    level_name: "L1"
    path: [ [25.9, -24.10, 0.0],
            [25.3, -23.1, 1.57],
            [25.3, -25.4, 0.0],
            [24.8, -28.2, 0.0],
            [23.5, -24.5, 0.0] ]
    finish_waypoint: "clean_zone"
