- operation: Add
  participant_description:
    name: tinyRobot2
    group: tinyRobot
    responsiveness: Responsive
    profile:
      footprint:
        type: Circle
        index: "\x00"
      vicinity:
        type: Circle
        index: "\x01"
      shape_context:
        - 0.3
        - 0.5
- operation: Add
  participant_description:
    name: tinyRobot1
    group: tinyRobot
    responsiveness: Responsive
    profile:
      footprint:
        type: Circle
        index: "\x00"
      vicinity:
        type: Circle
        index: "\x01"
      shape_context:
        - 0.3
        - 0.5
- operation: Add
  participant_description:
    name: cleanerBotA_1
    group: cleanerBotA
    responsiveness: Responsive
    profile:
      footprint:
        type: Circle
        index: "\x00"
      vicinity:
        type: Circle
        index: "\x01"
      shape_context:
        - 1
        - 1.2
- operation: Add
  participant_description:
    name: AiMbot1
    group: AiMbot
    responsiveness: Responsive
    profile:
      footprint:
        type: Circle
        index: "\x00"
      vicinity:
        type: Circle
        index: "\x01"
      shape_context:
        - 0.3
        - 0.5